### ISSUE TITLE
"Background Species" function

### ISSUE THREAD

**Issue by LeiXing0726** [osmose-model/osmose#8]
Hi Nicolas,
Recently, I attempted to employ the "Background Species" function. The model did not run with the errors: 
Exception in thread "main" java.lang.NullPointerException
	at fr.ird.osmose.background.BackgroundMapSet.checkMapIndexation(BackgroundMapSet.java:296)
	at fr.ird.osmose.background.BackgroundMapSet.loadMaps(BackgroundMapSet.java:118)
	at fr.ird.osmose.background.BackgroundSpecies.<init>(BackgroundSpecies.java:85)
	at fr.ird.osmose.Configuration.init(Configuration.java:410)
	at fr.ird.osmose.Osmose.runConfiguration(Osmose.java:327)
	at fr.ird.osmose.Osmose.run(Osmose.java:269)
	at fr.ird.osmose.Osmose.main(Osmose.java:490)
I guess the model failed to read the movement map for the background species (BK0). Would you please help me check the problem? The version is 4.1.0. 
Thank you in advance. I am looking forward to your letter.
Best,
Lei

PS: I fail to upload the zip file of model configuration as the zip file is not inclued in the list of upload file type. I sent the file to your e-mail (nicolas.barrier@ird.fr).
![image](https://user-images.githubusercontent.com/68097411/124091578-9418e900-da88-11eb-91b3-4259825aec3b.png)

**Comment by barriern** [comment]
Hi Lei.

Sorry for the late response. There were two problems:
- There was an error in the configuration file of background species. I join a corrected version of the file.
- There were bugs in the management of background species in v4.1.0. These bugs were removed in the most recent versions of Osmose, because the management of background species has completely changed. However, I give you a corrected `.jar` file that contains the bugfix,

Nicolas

[osm_param-background.csv.txt](https://github.com/osmose-model/osmose/files/6823101/osm_param-background.csv.txt)
[osmose_4.1.0.zip](https://github.com/osmose-model/osmose/files/6823116/osmose_4.1.0.zip)

**Comment by LeiXing0726** [comment]
Hi Nicolas,
Thank you for your kind help. The model runs successfully with the new osmose_4.1.0.jar. 
When the "output.diet.composition.enabled" was set to "false", the model ran and the output files created.
When the "output.diet.composition.enabled" was set to "true", the model ran but the output files failed to create. The errors were as below:
osmose[info] *********************************************
java.lang.ArrayIndexOutOfBoundsException: 9
	at fr.ird.osmose.output.DietOutput.update(DietOutput.java:125)
	at fr.ird.osmose.output.OutputManager.update(OutputManager.java:357)
	at fr.ird.osmose.step.DefaultStep.step(DefaultStep.java:165)
	at fr.ird.osmose.Simulation.run(Simulation.java:296)
	at fr.ird.osmose.Osmose$Worker.run(Osmose.java:417)
	at java.lang.Thread.run(Unknown Source)

I guess there are something wrong with creating the diet csv. Would you please help me check this problem?  I am looking forward to your reply.

Best wishes,

Lei

**Comment by LeiXing0726** [comment]
Hi Nicolas,
Thank you for your kind help. The model runs successfully with the new osmose_4.1.0.jar. 
When the "output.diet.composition.enabled" was set to "false", the model ran and the output files created.
When the "output.diet.composition.enabled" was set to "true", the model ran but the output files failed to create. The errors were as below:
osmose[info] *********************************************
java.lang.ArrayIndexOutOfBoundsException: 9
	at fr.ird.osmose.output.DietOutput.update(DietOutput.java:125)
	at fr.ird.osmose.output.OutputManager.update(OutputManager.java:357)
	at fr.ird.osmose.step.DefaultStep.step(DefaultStep.java:165)
	at fr.ird.osmose.Simulation.run(Simulation.java:296)
	at fr.ird.osmose.Osmose$Worker.run(Osmose.java:417)
	at java.lang.Thread.run(Unknown Source)

I guess there are something wrong with creating the diet csv. Would you please help me check this problem?  I am looking forward to your reply.

Best wishes,

Lei

**Comment by barriern** [comment]
Hi Lei.

Could it be possible for you to migrate to the newest version of Osmose (4.3.2)? I have invited you to the private Osmose repository:

https://github.com/osmose-model/osmose-private

It would be easiest for me since because you are using a too old implementation of background species. And most of the bugs you will meet have been corrected in the new implementation.

Thanks

Nicolas

**Comment by LeiXing0726** [comment]
Hi Nicolas,
Thanks for your help. Recently, I could not install the OSMOSE package from github with the code "devtools::install_github("osmose-model/osmose")". The reason may be the restriction of network (I can read the files but fail to download from github). The model calibration needs to library the OSMOSE package.  Would you please send a tar.gz file of OSMOSE package to me? 
Best,
Lei













At 2021-08-05 15:53:36, "Nicolas Barrier" ***@***.***> wrote:

Hi Lei.

Could it be possible for you to migrate to the newest version of Osmose (4.3.2)? I have invited you to the private Osmose repository:

https://github.com/osmose-model/osmose-private

It would be easiest for me since because you are using a too old implementation of background species. And most of the bugs you will meet have been corrected in the new implementation.

Thanks

Nicolas

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by barriern** [comment]
Hi Lei. Which version do you need? Be carefull though, using the R command allows you to download only the public version of Osmose, which is late compared to the private one.

**Comment by LeiXing0726** [comment]
Hi Nicolas, 
The jar version which I currently use is osmose_4.1.0.jar. I run the model using the R code which has defined the path of osmose_4.1.0.jar in my PC. 
The calibration developed by OSMOSE team is launched by the packages "calibrar" and "osmose". I cannot directly update them from github. The "calibrar" and "osmose" which I currently use need to update.  I need the tar.gz files for the two packages.
Thanks.
Lei

**Comment by barriern** [comment]
Hi @LeiXing0726 

I am looking at the different opened issues and noticed that I did not answer to your last message here, but maybe I did so by email. If it is the case, can I close the issue?

Cheers

@barriern

**Comment by LeiXing0726** [comment]
> Hi @LeiXing0726
> 
> I am looking at the different opened issues and noticed that I did not answer to your last message here, but maybe I did so by email. If it is the case, can I close the issue?
> 
> Cheers
> 
> @barriern

Hi Nicolas,
Sorry for the late response. This issue can be closed. Would you please provide the example of  background speceis configuration?  Thank you in advance.
Cheers,
Lei

**Comment by barriern** [comment]
Hi @LeiXing0726 

Here are the parameters that you may need for the background species:

```
species.name.sp12;HarbourSeals
species.type.sp12;background
species.length2weight.allometric.power.sp12;3
species.length2weight.condition.factor.sp12;0.01
species.file.sp12;python/bkgbiomass-HarbourSeals.nc
species.size.proportion.file.sp12;python/bkgpercentage-HarbourSeals.csv
species.nclass.sp12;1
species.trophic.level.sp12;4.5
species.age.sp12;2.5
species.length.sp12;138
#biomass.byDt.bySize.file.sp12;bkgbiomass/bkgbiomass-HarbourSeals.csv
species.biomass.nsteps.year.sp12;24
species.file.caching.sp12;none
predation.efficiency.critical.sp12;0.57
predation.ingestion.rate.max.sp12;13.6
predation.predPrey.sizeRatio.max.sp12;5
predation.predPrey.sizeRatio.min.sp12;40
```

The NetCDF file provides the total biomass and the `bkgpercentage-HarbourSeals.csv` file provides the proportion for each size-class considered.

Cheers,

@barriern

**Comment by barriern** [comment]
By the way sorry @LeiXing0726 I deleted by mistake your latest comment...

**Comment by salifu3590** [comment]
Thank you for your reply Dr Lei, i am just a beginner to OSMOSE. My background species are yellowfin tuna. consider the attached CSV file.

2023-08-16 09:50:37"LeiXing0726" ***@***.***>wrote:

Hi @LeiXing0726

I am looking at the different opened issues and noticed that I did not answer to your last message here, but maybe I did so by email. If it is the case, can I close the issue?

Cheers

@barriern

Hi Nicolas,
Sorry for the late response. This issue can be closed. Would you please provide the example of background speceis configuration? Thank you in advance.
Cheers,
Lei
